config/routes.rb
Rails.application.routes.draw do
  get 'links/create'
  get 'links/create'
  get 'links/destroy'
  devise_for :users
  root to: "favorites#index"

  get 'favorites/convinient' =>'favorites#convinient'
  get 'favorites/sns' =>'favorites#sns'
  get 'favorites/hobby' =>'favorites#hobby'
  get 'favorites/bussiness' =>'favorites#bussiness'
  get 'favorites/shopping' =>'favorites#shopping'
  get 'favorites/other' =>'favorites#other'


  resources :favorites do
    collection do
      get 'search'
    end
    resources :links, only: [:create, :destroy]
  end
  resources :users, only: [:show,:edit, :update]

 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  include ActiveHash::Associations

  self.data = [
    {id: '', name: '選択してください'},
    {id: 1, name: "便利機能"},
    {id: 2, name: "SNS"},
    {id: 3, name:"趣味"},
    {id: 4, name: "ビジネス"},
    {id: 5, name: "買い物"},
    {id: 6, name: "その他"}
  ]
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  mount_uploader :image, ImageUploader

  validates :name,presence: true,length:{maximum: 20}
  validates :url,presence: true
  validates :image,presence: true
  validates :text,length:{maximum: 140}
  validates :category_id,presence: true

  belongs_to :user
  has_many :links, dependent: :destroy

  def link_user(user_id)
   links.find_by(user_id: user_id)
  end

  def self.search(search)
    return Favorite.all unless search
    Favorite.where(['name LIKE ?', "%#{search}%"])
  end
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
  belongs_to :favorite, counter_cache: :links_count
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name,presence: true,length:{maximum: 20},uniqueness: true

  has_many :favorite
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def index
    @recommended= Favorite.order("created_at DESC").where('user_id IS NULL')
  end

  def new
    @favorite= Favorite.new
  end

  def create
    @favorite= Favorite.new(favorite_params)
    if @favorite.save
      redirect_to user_path(current_user),notice: "#{@favorite.name}を登録しました"
    else
      render 'new'
    end
  end

  def edit
    @favorite= Favorite.find(params[:id])
  end

  def update
    @favorite= Favorite.find(params[:id])
    if @favorite.update(favorite_params)
      redirect_to user_path(current_user),notice: "#{@favorite.name}を編集しました"
    else
      render 'edit'
    end
  end

  def destroy
    favorite= Favorite.find(params[:id])
    if favorite.user_id == current_user.id
      favorite.destroy
      redirect_to user_path(current_user),notice: "お気に入りを削除しました"
    end
  end

  def search
    @users = current_user.id
    @favorites = Favorite.search(params[:search])
    sort = params[:sort] || "created_at DESC"
    @current_user_favorites=@favorites.where(user_id:@users).page(params[:page]).per(48).order(sort)
  end

  def convinient
    @users=User.find(current_user.id)
    @convinients= @users.favorite.where(category_id:'1').order("links_count desc").page(params[:page]).per(48)
  
  end

  def sns
    @users=User.find(current_user.id)
    @snses= @users.favorite.where(category_id:'2').order("links_count desc").page(params[:page]).per(48)
  end

  def hobby
    @users=User.find(current_user.id)
    @hobbys= @users.favorite.where(category_id:'3').order("links_count desc").page(params[:page]).per(48)
  end

  def bussiness
    @users=User.find(current_user.id)
    @bussinesses= @users.favorite.where(category_id:'4').order("links_count desc").page(params[:page]).per(48)
  end

  def shopping
    @users=User.find(current_user.id)
    @shoppings= @users.favorite.where(category_id:'5').order("links_count desc").page(params[:page]).per(48)
  end
  
  def other
    @users=User.find(current_user.id)
    @others= @users.favorite.where(category_id:'6').order("links_count desc").page(params[:page]).per(48)
  end

  private
  def favorite_params
    params.require(:favorite).permit(:name,:url,:category_id,:image,:text).merge(user_id: current_user.id)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_favorite

  def create
    @link = Link.create(user_id: current_user.id, favorite_id: params[:favorite_id])
    @links = Link.where(favorite_id: params[:favorite_id])
    @favorite.reload
  end

  def destroy
    link = Link.find_by(user_id: current_user.id, favorite_id: params[:favorite_id])
    link.destroy
    @links = Link.where(favorite_id: params[:favorite_id])
    @favorite.reload
  end

  private

  def set_favorite
    @favorite = Favorite.find(params[:favorite_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @users=User.find(params[:id])
    @favorites= @users.favorite.order("category_id ASC").page(params[:page]).per(48)
    @convenient=@favorites.where(category_id:'1')
    @sns=@favorites.where(category_id:'2')
    @hobby=@favorites.where(category_id:'3')
    @bussiness=@favorites.where(category_id:'4')
    @shopping=@favorites.where(category_id:'5')
    @other=@favorites.where(category_id:'6')
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path,notice:'アカウントが編集されました'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/favorites/_error_messages.html.haml
- if favorite.errors.any?
  .alert.alert-danger.container-fluid
    %ul
      - favorite.errors.full_messages.each do |message|
        %li= message

app/views/favorites/_footer.html.haml
%nav.navbar.navbar-expand-md.navbar-dark.bg-warning
  .container
    #navbar-content.collapse.navbar-collapse.justify-content-center
      %ul.navbar-nav
        %li.nav-item.active
          = link_to "お気に入り登録",new_favorite_path,class: "nav-link"
        %li.nav-item
          = link_to "マイページ",user_path(current_user),class: "nav-link"
        %li.nav-item
          = link_to "アカウント編集",edit_user_path(current_user),class: "nav-link"
        %li.nav-item
          =link_to "ログアウト", destroy_user_session_path, method: :delete,class: "nav-link header-link", data: { confirm: 'ログアウトしますか？' }
%p.text-center Copyright ©2019 Favorites, All Rights Reserved.
       

app/views/favorites/_header.html.haml
%nav.navbar.navbar-expand-md.navbar-dark.bg-warning.sticky-top
  .header
    .content-top
      %a.site-name{:href => "/"} Favorites
      .navbar-search
        =form_tag search_favorites_path,class: "header-form", method: 'get'  do
          %button.fa.fa-search{type: "submit"}
          = text_field_tag :search,params[:search],class: "header-field",placeholder: "お気に入りを検索" 
    .content-bottom
      %button.navbar-toggler{"aria-controls" => "navbar-content", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbar-content", "data-toggle" => "collapse", :type => "button"}
        %span.navbar-toggler-icon
      #navbar-content.collapse.navbar-collapse.justify-content-end
        %ul.navbar-nav
         
          %li.dropdown
            %a.dropdown-toggle.nav-link.active{"data-toggle" => "dropdown", :href => "#"}
              マイページ
              %span.caret
            %ul.dropdown-menu{:role => "menu"}
              %li
                = link_to "登録サイト一覧",user_path(current_user),class:"a text-dark"
              %li
                = link_to "便利機能",favorites_convinient_path(current_user),class:"text-dark"
              %li
                = link_to "SNS",favorites_sns_path(current_user),class:"text-dark"
              %li
                = link_to "趣味",favorites_hobby_path(current_user),class:"text-dark"
              %li
                = link_to "ビジネス",favorites_bussiness_path(current_user),class:"text-dark"
              %li
                = link_to "買い物",favorites_shopping_path(current_user),class:"text-dark"
              %li
                = link_to "その他",favorites_other_path(current_user),class:"text-dark"
          %li.nav-item.active
            = link_to "お気に入り登録",new_favorite_path,class: "nav-link"
          %li.nav-item.active
            = link_to "アカウント編集",edit_user_path(current_user),class: "nav-link"
          %li.nav-item.active
            =link_to "ログアウト", destroy_user_session_path, method: :delete,class: "nav-link header-link", data: { confirm: 'ログアウトしますか？' }


      .content-right
        
  
      
    
  

app/views/favorites/bussiness.html.haml
%body
  =render 'favorites/header'

  .py-0
    %section#registrationsite
    .container
      %h3.mb-h3.text-center
        = current_user.name+"さんのページ"
      .content
        %h4.mb-h4 ビジネス
        .category-area
          - @bussinesses.each do |favorite|
            .col-sm-6.col-md-3
              .card.img-thumbnail
                .links-count-area
                  .links-count-area__circle
                    .links-count-area__circle__text
                      -if favorite.links_count==nil||favorite.links_count==0
                        = "0"
                      -elsif favorite.links_count>0&&favorite.links_count<10000
                        = favorite.links_count
                      - else
                        = "+9999"
                .image-area
                  %a{"data-target" => "#modal#{favorite.id}","data-toggle" => "modal"}
                    %img.btn.card-img-thumbnail{:alt => "画像", :src => favorite.image}
                .card-body.px-2.py-3
                  %h5.card-text.text-center= favorite.name

            .modal.fade{"aria-hidden" => "true", "aria-labelledby" => "modal01-label", :role => "dialog", :tabindex => "-1", id: "modal#{favorite.id}"}
              .modal-dialog.modal-dialog-centered{:role => "document"}
                .modal-content
                  .modal-header
                    %h5#modal01-label.modal-title= favorite.name
                    %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
                      %span{"aria-hidden" => "true"} ×
                  .modal-body
                    %p.text-center
                      %a{:href => favorite.url}
                        %img.img-fluid{:alt => "#", :src => favorite.image,"data-toggle"=>"tooltip","data-placement"=>"top","title"=>"クリックすると#{favorite.name}に飛びます"}
                      %div{:id => "links_buttons_#{favorite.id}"}
                        = render partial: 'links/link', locals: { favorite: favorite, links: @links}
                      = favorite.text
                  .modal-footer
                    =link_to '編集',edit_favorite_path(favorite),class: 'btn btn-warning'
                    %a.btn.btn-warning{"data-target" => "#delete#{favorite.id}","data-toggle" => "modal","data-dismiss" => "modal"} 削除
                
                .modal.fade{"aria-hidden" => "true", "aria-labelledby" => "modal02-label", :role => "dialog", :tabindex => "-1", id: "delete#{favorite.id}"}
                  .modal-dialog.modal-dialog-centered{:role => "document"}
                    .modal-content
                      .modal-header
                        %h5#modal01-label.modal-title 削除確認画面
                        %button.close{"aria-label" => "Close", "data-dismiss" => "modal"}
                          %span{"aria-hidden" => "true"} ×
                      .modal-body
                        %p.text-center
                          %img.img-fluid{:alt => "#", :src => favorite.image}
                          %p.text-center #{favorite.name}を削除しますか？
                      .modal-footer
                        =link_to '削除',favorite_path(favorite.id),method: :delete, class: 'btn btn-warning'
        
        

      .paginate-area
        =paginate @bussinesses
        =page_entries_info @bussinesses
.footer.bg-warning.text-light.fixed-bottom
  =render 'favorites/footer'

app/views/favorites/convinient.html.haml
%body
  =render 'favorites/header'

  .py-0
    %section#registrationsite
    .container
      %h3.mb-h3.text-center
        = current_user.name+"さんのページ"
      .content
        %h4.mb-h4 便利機能
        .category-area
          - @convinients.each do |favorite|
            .col-sm-6.col-md-3
              .card.img-thumbnail
                .links-count-area
                  .links-count-area__circle
                    .links-count-area__circle__text
                      -if favorite.links_count==nil||favorite.links_count==0
                        = "0"
                      -elsif favorite.links_count>0&&favorite.links_count<10000
                        = favorite.links_count
                      - else
                        = "+9999"
                .image-area
                  %a{"data-target" => "#modal#{favorite.id}","data-toggle" => "modal"}
                    %img.btn.card-img-thumbnail{:alt => "画像", :src => favorite.image}
                .card-body.px-2.py-3
                  %h5.card-text.text-center= favorite.name

            .modal.fade{"aria-hidden" => "true", "aria-labelledby" => "modal01-label", :role => "dialog", :tabindex => "-1", id: "modal#{favorite.id}"}
              .modal-dialog.modal-dialog-centered{:role => "document"}
                .modal-content
                  .modal-header
                    %h5#modal01-label.modal-title= favorite.name
                    %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
                      %span{"aria-hidden" => "true"} ×
                  .modal-body
                    %p.text-center
                      %a{:href => favorite.url}
                        %img.img-fluid{:alt => "#", :src => favorite.image,"data-toggle"=>"tooltip","data-placement"=>"top","title"=>"クリックすると#{favorite.name}に飛びます"}
                      %div{:id => "links_buttons_#{favorite.id}"}
                        = render partial: 'links/link', locals: { favorite: favorite, links: @links}
                      = favorite.text
                  .modal-footer
                    =link_to '編集',edit_favorite_path(favorite),class: 'btn btn-warning'
                    %a.btn.btn-warning{"data-target" => "#delete#{favorite.id}","data-toggle" => "modal","data-dismiss" => "modal"} 削除
                
                .modal.fade{"aria-hidden" => "true", "aria-labelledby" => "modal02-label", :role => "dialog", :tabindex => "-1", id: "delete#{favorite.id}"}
                  .modal-dialog.modal-dialog-centered{:role => "document"}
                    .modal-content
                      .modal-header
                        %h5#modal01-label.modal-title 削除確認画面
                        %button.close{"aria-label" => "Close", "data-dismiss" => "modal"}
                          %span{"aria-hidden" => "true"} ×
                      .modal-body
                        %p.text-center
                          %img.img-fluid{:alt => "#", :src => favorite.image}
                          %p.text-center #{favorite.name}を削除しますか？
                      .modal-footer
                        =link_to '削除',favorite_path(favorite.id),method: :delete, class: 'btn btn-warning'
        
        

      .paginate-area
        =paginate @convinients
        =page_entries_info @convinients
.footer.bg-warning.text-light.fixed-bottom
  =render 'favorites/footer'

app/views/favorites/hobby.html.haml
%body
  =render 'favorites/header'

  .py-0
    %section#registrationsite
    .container
      %h3.mb-h3.text-center
        = current_user.name+"さんのページ"
      .content
        %h4.mb-h4 趣味
        .category-area
          - @hobbys.each do |favorite|
            .col-sm-6.col-md-3
              .card.img-thumbnail
                .links-count-area
                  .links-count-area__circle
                    .links-count-area__circle__text
                      -if favorite.links_count==nil||favorite.links_count==0
                        = "0"
                      -elsif favorite.links_count>0&&favorite.links_count<10000
                        = favorite.links_count
                      - else
                        = "+9999"
                .image-area
                  %a{"data-target" => "#modal#{favorite.id}","data-toggle" => "modal"}
                    %img.btn.card-img-thumbnail{:alt => "画像", :src => favorite.image}
                .card-body.px-2.py-3
                  %h5.card-text.text-center= favorite.name

            .modal.fade{"aria-hidden" => "true", "aria-labelledby" => "modal01-label", :role => "dialog", :tabindex => "-1", id: "modal#{favorite.id}"}
              .modal-dialog.modal-dialog-centered{:role => "document"}
                .modal-content
                  .modal-header
                    %h5#modal01-label.modal-title= favorite.name
                    %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
                      %span{"aria-hidden" => "true"} ×
                  .modal-body
                    %p.text-center
                      %a{:href => favorite.url}
                        %img.img-fluid{:alt => "#", :src => favorite.image,"data-toggle"=>"tooltip","data-placement"=>"top","title"=>"クリックすると#{favorite.name}に飛びます"}
                      %div{:id => "links_buttons_#{favorite.id}"}
                        = render partial: 'links/link', locals: { favorite: favorite, links: @links}
                      = favorite.text
                  .modal-footer
                    =link_to '編集',edit_favorite_path(favorite),class: 'btn btn-warning'
                    %a.btn.btn-warning{"data-target" => "#delete#{favorite.id}","data-toggle" => "modal","data-dismiss" => "modal"} 削除
                
                .modal.fade{"aria-hidden" => "true", "aria-labelledby" => "modal02-label", :role => "dialog", :tabindex => "-1", id: "delete#{favorite.id}"}
                  .modal-dialog.modal-dialog-centered{:role => "document"}
                    .modal-content
                      .modal-header
                        %h5#modal01-label.modal-title 削除確認画面
                        %button.close{"aria-label" => "Close", "data-dismiss" => "modal"}
                          %span{"aria-hidden" => "true"} ×
                      .modal-body
                        %p.text-center
                          %img.img-fluid{:alt => "#", :src => favorite.image}
                          %p.text-center #{favorite.name}を削除しますか？
                      .modal-footer
                        =link_to '削除',favorite_path(favorite.id),method: :delete, class: 'btn btn-warning'
        
        

      .paginate-area
        =paginate @hobbys
        =page_entries_info @hobbys
.footer.bg-warning.text-light.fixed-bottom
  =render 'favorites/footer'

app/views/favorites/other.html.haml
%body
  =render 'favorites/header'

  .py-0
    %section#registrationsite
    .container
      %h3.mb-h3.text-center
        = current_user.name+"さんのページ"
      .content
        %h4.mb-h4 その他
        .category-area
          - @others.each do |favorite|
            .col-sm-6.col-md-3
              .card.img-thumbnail
                .links-count-area
                  .links-count-area__circle
                    .links-count-area__circle__text
                      -if favorite.links_count==nil||favorite.links_count==0
                        = "0"
                      -elsif favorite.links_count>0&&favorite.links_count<10000
                        = favorite.links_count
                      - else
                        = "+9999"
                .image-area
                  %a{"data-target" => "#modal#{favorite.id}","data-toggle" => "modal"}
                    %img.btn.card-img-thumbnail{:alt => "画像", :src => favorite.image}
                .card-body.px-2.py-3
                  %h5.card-text.text-center= favorite.name

            .modal.fade{"aria-hidden" => "true", "aria-labelledby" => "modal01-label", :role => "dialog", :tabindex => "-1", id: "modal#{favorite.id}"}
              .modal-dialog.modal-dialog-centered{:role => "document"}
                .modal-content
                  .modal-header
                    %h5#modal01-label.modal-title= favorite.name
                    %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
                      %span{"aria-hidden" => "true"} ×
                  .modal-body
                    %p.text-center
                      %a{:href => favorite.url}
                        %img.img-fluid{:alt => "#", :src => favorite.image,"data-toggle"=>"tooltip","data-placement"=>"top","title"=>"クリックすると#{favorite.name}に飛びます"}
                      %div{:id => "links_buttons_#{favorite.id}"}
                        = render partial: 'links/link', locals: { favorite: favorite, links: @links}
                      = favorite.text
                  .modal-footer
                    =link_to '編集',edit_favorite_path(favorite),class: 'btn btn-warning'
                    %a.btn.btn-warning{"data-target" => "#delete#{favorite.id}","data-toggle" => "modal","data-dismiss" => "modal"} 削除
                
                .modal.fade{"aria-hidden" => "true", "aria-labelledby" => "modal02-label", :role => "dialog", :tabindex => "-1", id: "delete#{favorite.id}"}
                  .modal-dialog.modal-dialog-centered{:role => "document"}
                    .modal-content
                      .modal-header
                        %h5#modal01-label.modal-title 削除確認画面
                        %button.close{"aria-label" => "Close", "data-dismiss" => "modal"}
                          %span{"aria-hidden" => "true"} ×
                      .modal-body
                        %p.text-center
                          %img.img-fluid{:alt => "#", :src => favorite.image}
                          %p.text-center #{favorite.name}を削除しますか？
                      .modal-footer
                        =link_to '削除',favorite_path(favorite.id),method: :delete, class: 'btn btn-warning'
        
        

      .paginate-area
        =paginate @others
        =page_entries_info @others
.footer.bg-warning.text-light.fixed-bottom
  =render 'favorites/footer'

app/views/favorites/search.html.haml
%body
  =render 'favorites/header'

  .py-0
    %section#registrationsite
    .container
      .content-title
        %h3.mb-h3 
          "&ensp;#{params[:search]}&ensp;"の検索結果
        %select{name: :sort_order, class: 'btn btn-default dropdown-toggle'}
          %option{value: "location.pathname", name: "location.pathname"}
            並び替え
          %option{value: "created_at_desc"}
            登録の新しい順
          %option{value: "created_at_asc"}
            登録の古い順
          %option{value: "links_count_desc"}
            使用回数の多い順
          %option{value: "links_count_asc"}
            使用回数の少ない順
      .row
        - @current_user_favorites.each do |favorite|
          .col-sm-6.col-md-3
            .card.img-thumbnail
              .links-count-area
                .links-count-area__circle
                  .links-count-area__circle__text
                    -if favorite.links_count==nil||favorite.links_count==0
                      = "0"
                    -elsif favorite.links_count>0&&favorite.links_count<10000
                      = favorite.links_count
                    - else
                      = "+9999"
              .image-area
                %a{"data-target" => "#modal#{favorite.id}","data-toggle" => "modal"}
                  %img.btn.card-img-thumbnail{:alt => "画像", :src => favorite.image}/
              .card-body.px-2.py-3
                %h5.card-text.text-center= favorite.name

            -# モーダル1(お気に入り詳細画面)
            .modal.fade{"aria-hidden" => "true", "aria-labelledby" => "modal01-label", :role => "dialog", :tabindex => "-1", id: "modal#{favorite.id}"}
              .modal-dialog.modal-dialog-centered{:role => "document"}
                .modal-content
                  .modal-header
                    %h5#modal01-label.modal-title= favorite.name
                    %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
                      %span{"aria-hidden" => "true"} ×
                  .modal-body
                    %p.text-center
                      %a{:href => favorite.url}
                        %img.img-fluid{:alt => "#", :src => favorite.image,"data-toggle"=>"tooltip","data-placement"=>"top","title"=>"クリックすると#{favorite.name}に飛びます" }
                      %div{:id => "links_buttons_#{favorite.id}"}
                        = render partial: 'links/link', locals: { favorite: favorite, links: @links}
                      = favorite.text
                  .modal-footer
                    =link_to '編集',edit_favorite_path(favorite),class: 'btn btn-warning'
                    %a.btn.btn-warning{"data-target" => "#delete#{favorite.id}","data-toggle" => "modal","data-dismiss" => "modal"} 削除
            -# モーダル2（お気に入り削除確認画面）
            .modal.fade{"aria-hidden" => "true", "aria-labelledby" => "modal02-label", :role => "dialog", :tabindex => "-1", id: "delete#{favorite.id}"}
              .modal-dialog.modal-dialog-centered{:role => "document"}
                .modal-content
                  .modal-header
                    %h5#modal01-label.modal-title 削除確認画面
                    %button.close{"aria-label" => "Close", "data-dismiss" => "modal"}
                      %span{"aria-hidden" => "true"} ×
                  .modal-body
                    %p.text-center
                      %img.img-fluid{:alt => "#", :src => favorite.image}
                      %p.text-center #{favorite.name}を削除しますか？
                  .modal-footer
                    =link_to '削除',favorite_path(favorite.id),method: :delete, class: 'btn btn-warning'
    
      .paginate-area
        =paginate @current_user_favorites
        =page_entries_info @current_user_favorites
  .footer.bg-warning.text-light.fixed-bottom
    =render 'favorites/footer'

app/views/favorites/shopping.html.haml
%body
  =render 'favorites/header'

  .py-0
    %section#registrationsite
    .container
      %h3.mb-h3.text-center
        = current_user.name+"さんのページ"
      .content
        %h4.mb-h4 買い物
        .category-area
          - @shoppings.each do |favorite|
            .col-sm-6.col-md-3
              .card.img-thumbnail
                .links-count-area
                  .links-count-area__circle
                    .links-count-area__circle__text
                      -if favorite.links_count==nil||favorite.links_count==0
                        = "0"
                      -elsif favorite.links_count>0&&favorite.links_count<10000
                        = favorite.links_count
                      - else
                        = "+9999"
                .image-area
                  %a{"data-target" => "#modal#{favorite.id}","data-toggle" => "modal"}
                    %img.btn.card-img-thumbnail{:alt => "画像", :src => favorite.image}
                .card-body.px-2.py-3
                  %h5.card-text.text-center= favorite.name

            .modal.fade{"aria-hidden" => "true", "aria-labelledby" => "modal01-label", :role => "dialog", :tabindex => "-1", id: "modal#{favorite.id}"}
              .modal-dialog.modal-dialog-centered{:role => "document"}
                .modal-content
                  .modal-header
                    %h5#modal01-label.modal-title= favorite.name
                    %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
                      %span{"aria-hidden" => "true"} ×
                  .modal-body
                    %p.text-center
                      %a{:href => favorite.url}
                        %img.img-fluid{:alt => "#", :src => favorite.image,"data-toggle"=>"tooltip","data-placement"=>"top","title"=>"クリックすると#{favorite.name}に飛びます"}
                      %div{:id => "links_buttons_#{favorite.id}"}
                        = render partial: 'links/link', locals: { favorite: favorite, links: @links}
                      = favorite.text
                  .modal-footer
                    =link_to '編集',edit_favorite_path(favorite),class: 'btn btn-warning'
                    %a.btn.btn-warning{"data-target" => "#delete#{favorite.id}","data-toggle" => "modal","data-dismiss" => "modal"} 削除
                
                .modal.fade{"aria-hidden" => "true", "aria-labelledby" => "modal02-label", :role => "dialog", :tabindex => "-1", id: "delete#{favorite.id}"}
                  .modal-dialog.modal-dialog-centered{:role => "document"}
                    .modal-content
                      .modal-header
                        %h5#modal01-label.modal-title 削除確認画面
                        %button.close{"aria-label" => "Close", "data-dismiss" => "modal"}
                          %span{"aria-hidden" => "true"} ×
                      .modal-body
                        %p.text-center
                          %img.img-fluid{:alt => "#", :src => favorite.image}
                          %p.text-center #{favorite.name}を削除しますか？
                      .modal-footer
                        =link_to '削除',favorite_path(favorite.id),method: :delete, class: 'btn btn-warning'
        
        

      .paginate-area
        =paginate @shoppings
        =page_entries_info @shoppings
.footer.bg-warning.text-light.fixed-bottom
  =render 'favorites/footer'